version: "3.8"

services:
 postgresdb:
  image: postgres
  restart: unless-stopped
  environment:
   - POSTGRES_USER=$POSTGRESDB_USER
   - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
   - POSTGRES_DB=$POSTGRESDB_DATABASE
  ports:
   - 8080:5432
  volumes:
   - db:/var/lib/postgresql/data

volumes:
 db:
