version: "3.9"

services:
 db:
  image: postgres:13
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=pass123
   - POSTGRES_DB=user_audit_trail
  volumes:
   - db-data:/var/lib/postgresql/data
  networks:
   - app-network
  ports:
   - 65432:65432

networks:
 app-network:
  driver: bridge

volumes:
 db-data:
