version: "3.8"

services:
 postgresdb:
  image: postgres
  restart: unless-stopped
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=pass123
   - POSTGRES_DB=user_audit_trail
  ports:
   - 8080:5432
  volumes:
   - db:/var/lib/postgresql/data

volumes:
 db:
